import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NabBar from "./components/NavBar";
import StyledComponentsRegistry from "./lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yarn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <NabBar />

          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
